apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - verifier.yaml
configMapGenerator:
  - name: verifier-trust-job
    namespace: argos-services
    files:
      - trust.py
