"""ARG-091 · the alert rules of ARGOS, written from the table of objectives (F10-03).

    uv run python tools/alert_rules.py [--check]

Reads platform/observability/objectives.yaml and writes
platform/observability/rules/argos.rules.yml: one alert per objective that has an expression.
The objectives whose alert lives in an earlier rule file (`existing`) and those still `pending`
are not written here. `--check` fails when the file on disk is not what the table gives.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[1]
OBJECTIVES = REPO / "platform" / "observability" / "objectives.yaml"
RULES = REPO / "platform" / "observability" / "rules" / "argos.rules.yml"
HEADER = (
    "# GENERATED by tools/alert_rules.py from platform/observability/objectives.yaml.\n"
    "# Do not edit it: change the table and run make alert-rules.\n"
    "# ARG-091 (F10-03): each measurable objective of the specification, watched. The tests of\n"
    "# these rules are in tests/observability/argos_rules_test.yml.\n"
)
SEVERITIES = {"critical", "warning"}


def _rule(objective: Mapping[str, Any]) -> dict[str, Any]:
    name = str(objective.get("id"))
    runbook = str(objective.get("runbook") or "")
    if not runbook:
        raise ValueError(f"objective {name} has no runbook")
    if objective.get("severity") not in SEVERITIES:
        raise ValueError(f"objective {name} has no valid severity")
    rule: dict[str, Any] = {"alert": str(objective["alert"]), "expr": str(objective["expr"])}
    if objective.get("for"):
        rule["for"] = str(objective["for"])
    rule["labels"] = {"severity": str(objective["severity"]), "objective": name}
    rule["annotations"] = {
        "summary": str(objective["summary"]),
        "description": str(objective["description"]),
        "runbook_url": runbook,
        "source": str(objective["source"]),
    }
    return rule


def render(objectives: Sequence[Mapping[str, Any]]) -> str:
    rules = [
        _rule(o)
        for o in objectives
        if o.get("alert") and not o.get("existing") and not o.get("pending")
    ]
    document = {"groups": [{"name": "argos-domain", "rules": rules}]}
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True, width=100)
    return HEADER + body


def load(path: Path = OBJECTIVES) -> list[dict[str, Any]]:
    return list(yaml.safe_load(path.read_text(encoding="utf-8"))["objectives"])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the rules are not up to date")
    args = parser.parse_args(argv)
    text = render(load())
    if args.check:
        if RULES.read_text(encoding="utf-8") != text:
            print(f"{RULES} is not up to date: run tools/alert_rules.py", file=sys.stderr)
            return 1
        print("the alert rules are up to date")
        return 0
    RULES.write_text(text, encoding="utf-8", newline="\n")
    print(f"{RULES.relative_to(REPO)} written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
